version: "3.4"
services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    links:
      - api
  api:
    build: ./api
    restart: always
    ports:
      - "9000:9000"
  mongo:
    image: mongo
    restart: always
